name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker build
      run: docker build -t $DOCKER_REGISTRY/nodejs-new:latest .
      env:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
    - name: docker push
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/nodejs:latest
    - name: nodejs-scan
      uses: ajinabraham/njsscan-action@v6
      with:
        args: '. --sarif --output results.sarif || true'
    - name: Upload njsscan report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
